<?php

namespace ContainerOoqVlZx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NiycchkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Niycchk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Niycchk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.Niycchk.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.Niycchk": it references class "App\\Entity\\Product" but no such service exists.'],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'product' => 'App\\Entity\\Product',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
