<?php

namespace ContainerOoqVlZx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bw8tvv2.App\Entity\Category' shared service.
     *
     * @return \App\Entity\Category
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bw8tvv2": it references class "App\\Entity\\Category" but no such service exists.');
    }
}
