<?php

namespace ContainerVoHjhfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_GOxvONService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.GOxvON_' shared service.
     *
     * @return \Swift_Mailer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DefaultController::index()": the $mailer argument is type-hinted with the non-existent class or interface: "Swift_Mailer".');
    }
}
